[package]
name = "enrender"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encore = {path = "../encore"}
winit = "0.25.0"
wgpu = "0.11.0"
futures = "0.3.17"