[package]
name = "magick_science"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enwin = {path = "enwin"}

[workspace]
members = [
    "enwin"
]
